$(document).ready(function(){
    $('.toggle-night').click(function(){
        $('.toggle-night').toggleClass('active')
        $('body').toggleClass('night')
        $('.tox-edit-area__iframe').toggleClass('night')
        $('.mce-content-body').toggleClass('night')
        $('.tox-menubar').toggleClass('night')
        $('.tox-mbtn__select-label').toggleClass('night')
        $('.tox-toolbar__primary').toggleClass('night')
        $('.tox-tbtn').toggleClass('night')
        $('.tox-tbtn__select-label').toggleClass('night')
        $('.tox-mbtn--select').toggleClass('night')
        $('.tox-toolbar__group').toggleClass('night')
        $('.tox-collection__group').toggleClass('night')
        $('.editor-header__home__text').toggleClass('night')
        $('.editor-area__list__number').toggleClass('night')
        $('.editor-area__list__title').toggleClass('night')
        $('.editor-header__home__icon__img').toggleClass('night')
        $('.editor-popper-button_dots').toggleClass('night')
        $('.help__icon').toggleClass('night')
        $('.editor-popper-button_people').toggleClass('night')
        $('.editor-area__title').toggleClass('night')
        $('.editor-header__home__icon').toggleClass('night')
        $('.button-editor').toggleClass('night')
        $('.editor-popper').toggleClass('night')
        $('#editor-popup-arrow').toggleClass('night')
        $('.editor-popper__night-mode__text').toggleClass('night')
        $('.h5__sidebar-series').toggleClass('night')
        $('.sidebar-series__item__number').toggleClass('night')
        $('.sidebar-series__item__title').toggleClass('night')
        $('.tox-collection__item-label').toggleClass('night')
    })
})



